### ISSUE TITLE
SSL error when redirecting from HTTP to HTTPS

### ISSUE THREAD

**Issue by mbaig25** [vfarcic/docker-flow-proxy#122]
I'm not sure if this is right place to post this, but I had to ask someone.

I've been trying to get SSL to work with Flow proxy using the [docker-flow-letsencrypt](https://github.com/hamburml/docker-flow-letsencrypt) companion. I'm trying to do this in a swarm. But I always get the following error:
```sh
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

I am starting the Flow proxy, swarm listener, letsencrypt companion, and my NodeJs application in the following way and order:
```sh
docker service create --name swarm-listener \
    --network proxy \
    --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
    -e DF_NOTIF_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure \
    -e DF_NOTIF_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove \
    --constraint 'node.role == manager' \
    vfarcic/docker-flow-swarm-listener
```
```sh
docker service create --name proxy \
    -p 80:80 \
    -p 443:443 \
    -p 8080:8080 \
    --network proxy \
    --constraint 'node.role == manager' \
    -e MODE=swarm \
    -e LISTENER_ADDRESS=swarm-listener \
    vfarcic/docker-flow-proxy
```
```sh
docker service create --name letsencrypt-companion \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/.well-known/acme-challenge \
    --label com.df.port=80 \
    -e DOMAIN_1="('customdomain.local' 'www.customdomain.local')"\
    -e DOMAIN_COUNT=1 \
    -e CERTBOT_EMAIL="<email>" \
    -e PROXY_ADDRESS="proxy" \
    -e CERTBOT_CRON_RENEW="('0 3 * * *' '0 15 * * *')"\
    --network proxy \
    --mount type=bind,source=/etc/letsencrypt,destination=/etc/letsencrypt \
    --constraint 'node.id == js29rzr2dwkkzcfylt8yqtv91' \
    --replicas 1 hamburml/docker-flow-letsencrypt:latest
```
```sh
docker service create --name nodeapp \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/ \
    --label com.df.port=8080 \
    --label com.df.httpsOnly=true \
    --network proxy \
    --network application \
    --constraint 'node.role == worker' \
    --replicas 2 \
    mbaig25/nodeapp
```

My NodeJs app is a simple hello world example:
```js
const Express = require(`express`);
const ip = require(`ip`);
const bodyParser = require(`body-parser`);
const compression = require(`compression`);
const helmet = require(`helmet`);
const winston = require(`winston`);

const app = new Express();
const logger = new winston.Logger({
    transports: [
        new (winston.transports.Console)({
            colorize: true,
            timestamp: () => new Date().toLocaleString(),
        }),
    ],
});

// Use to specify different settings for production
if (app.settings.env === `production`) {
    app.prod = true;
}

app.set(`trust proxy`, true);
app.use(compression()); // Better performance
app.use(helmet()); // Better security
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: true,
}));

app.listen(8080, () => {
    logger.info(`Started server: http://${ip.address()}:8080`);
});

app.get(`/`, (req, res) => {
    res.send(`hello world`);
});

module.exports = app;
```

The swarm has one manager and two workers. The proxy, listener, and letsencrypt-companion are all on the manager node.

When I have everything up and running, I use the following curl command to test:
```sh
curl -i -H "Host: customdomain.local" -L --verbose $(docker-machine ip swarm-manager-1)
```
Which produces this output:
```sh
* Rebuilt URL to: 192.168.99.100/
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connected to 192.168.99.100 (192.168.99.100) port 80 (#0)
> GET / HTTP/1.1
> Host: customdomain.local
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 302 Found
HTTP/1.1 302 Found
< Cache-Control: no-cache
Cache-Control: no-cache
< Content-length: 0
Content-length: 0
< Location: https://customdomain.local/
Location: https://customdomain.local/
< Connection: close
Connection: close

< 
* Curl_http_done: called premature == 0
* Closing connection 0
* Issue another request to this URL: 'https://customdomain.local/'
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connected to customdomain.local (192.168.99.100) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
* Curl_http_done: called premature == 1
* Closing connection 1
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

After everything is started, the final `haproxy.cfg` file looks like this:
```
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    #disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-server-close
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s

    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats auth admin:admin
    stats uri /admin?stats

frontend services
    bind *:80
    bind *:443
    mode http

    acl url_letsencrypt-companion80 path_beg /.well-known/acme-challenge
    use_backend letsencrypt-companion-be80 if url_letsencrypt-companion80
    acl url_nodeapp8080 path_beg /
    redirect scheme https if !{ ssl_fc } url_nodeapp8080
    use_backend nodeapp-be8080 if url_nodeapp8080






backend letsencrypt-companion-be80
    mode http
    server letsencrypt-companion letsencrypt-companion:80


backend nodeapp-be8080
    mode http
    server nodeapp nodeapp:8080
```

I already have `customdomain.local` in my `/etc/hosts` pointing to manager machine's ip address.

Any help with this would be appreciated.

Thank you.

**Comment by hamburml** [comment]
I can directly see that the letsencrypt companion didn't finish it work because your config is missing the certificates. Normally it shoud look like

`bind *:443 ssl crt /certs/<domain>.combined.pem `

**Comment by mbaig25** [comment]
@hamburml Thanks for the response.

`customdomain.local` is just a placeholder that I have in my `/etc/hosts` file. If its the case that it only works with real domains registered on a name server then it seems that is my issue.

Here are the logs located at `/var/log/letsencrypt`:
`letsencrypt.log`
```
2017-02-01 18:22:08,151:DEBUG:certbot.main:Root logging level set at 20
2017-02-01 18:22:08,151:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-02-01 18:22:08,152:DEBUG:certbot.main:certbot version: 0.10.2
2017-02-01 18:22:08,152:DEBUG:certbot.main:Arguments: []
2017-02-01 18:22:08,152:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-02-01 18:22:08,152:DEBUG:certbot.renewal:no renewal failures
```
`letsencrypt.log.1`
```
2017-02-01 18:22:06,084:DEBUG:certbot.main:Root logging level set at 20
2017-02-01 18:22:06,085:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-02-01 18:22:06,085:DEBUG:certbot.main:certbot version: 0.10.2
2017-02-01 18:22:06,085:DEBUG:certbot.main:Arguments: ['--standalone', '--non-interactive', '--cert-name', 'customdomain.local', '--expand', '--keep-until-expiring', '--email', '<email>', '-d', 'customdomain.local', '-d', 'www.customdomain.local', '--agree-tos', '--preferred-challenges', 'http-01', '--rsa-key-size', '4096', '--redirect', '--hsts', '--staple-ocsp']
2017-02-01 18:22:06,086:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-02-01 18:22:06,086:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2017-02-01 18:22:06,169:DEBUG:certbot.plugins.selection:Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f35b67e6fd0>
Prep: True
2017-02-01 18:22:06,170:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7f35b67e6fd0> and installer None
2017-02-01 18:22:06,175:DEBUG:certbot.main:Picked account: <Account(4667599d824979adf017a98996ad8fad)>
2017-02-01 18:22:06,175:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-02-01 18:22:06,178:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-02-01 18:22:06,459:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 352
2017-02-01 18:22:06,461:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 352
Boulder-Request-Id: uuTqYwgozjl7bOWc0QPiiartN5qfirMXoy49ZLZF02w
Replay-Nonce: bpw9neOCkLSVoRMiVsRzHp2Xpb7JcFZ-R0Tq6a2ichI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Wed, 01 Feb 2017 18:22:06 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 01 Feb 2017 18:22:06 GMT
Connection: keep-alive

{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2017-02-01 18:22:06,462:INFO:certbot.main:Obtaining a new certificate
2017-02-01 18:22:06,463:DEBUG:root:Requesting fresh nonce
2017-02-01 18:22:06,463:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz.
2017-02-01 18:22:06,550:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "HEAD /acme/new-authz HTTP/1.1" 405 0
2017-02-01 18:22:06,552:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 91
Allow: POST
Boulder-Request-Id: QMtpTuUqqAUJA76kCvT8o0cheUMoRTBhFiwskaEYaVY
Replay-Nonce: f5VJTv3hebT8vuEiisGaoupb4hGE7WL3zfmjyiSVBlM
Expires: Wed, 01 Feb 2017 18:22:06 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 01 Feb 2017 18:22:06 GMT
Connection: keep-alive


2017-02-01 18:22:06,552:DEBUG:acme.client:Storing nonce: f5VJTv3hebT8vuEiisGaoupb4hGE7WL3zfmjyiSVBlM
2017-02-01 18:22:06,553:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns", 
    "value": "customdomain.local"
  }, 
  "resource": "new-authz"
}
2017-02-01 18:22:06,584:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "header": {
    "alg": "RS256", 
    "jwk": {
      "e": "AQAB", 
      "kty": "RSA", 
      "n": "tb_CULF7bkHRN7DCe2fIm5tt3aDfx2uTXM_ZWEQJJYJc33C3PADWxmAh6KvJ6gU3bgYqAPHMbYiBMIVa8deZdfpoPcA71ngTW7bvWhZcT8c-_5mHeBmYU_GQHiUuwXexxIyBMKRS2D5ehEGkEr6XCIC7evwA8iX1SgIpYhVbhwDg-07j663DGznY-2R5RmLxaHnhOf5hx97WgmL7JcuhHzlE-G8mqu2hwnMwyaogoJmcf8KGg2TZUAB8CmYbOnqtp9HINHMHcLH2RAPkxVZ8qdev6541Djz7WfeBvaCIllLmcZ0cKpLh37qUQSagRzrOaRtA6sZWlLzi8upuS_omxVlkNS-aKFLuIYSubEUg7P9a9MGHdxtTL6obSjJQdFoieb1wjGbYsZEJ_RQLxNSLFRH07F5sPNrFtkOlE67PJijVKA0jP_9nRz8NtDSzLvZ9h7R5GPuDkmWEMBCD_zNqgrW2oRZUvi2-lNewctn0u6lQcttaJLP6f_QWt63fnUMCdqOQ2dzfBfYhu_slp8iu0co44IyY1bb_fyRUkudSVYPliZPithFr4c1JL6XLzaSwNNe_vHTmECDQVKzsxYa9oPSreqr4_ukM9PaBnaEQC8X1GJ2cc-l0Mja8TUqVCymEt4FBHoQIB6NjxDWm9aROjxAhCa9KE_wEG0pntq97Mm0"
    }
  }, 
  "protected": "eyJub25jZSI6ICJmNVZKVHYzaGViVDh2dUVpaXNHYW91cGI0aEdFN1dMM3pmbWp5aVNWQmxNIn0", 
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAibWJhaWcyNS5sb2NhbCIKICB9LCAKICAicmVzb3VyY2UiOiAibmV3LWF1dGh6Igp9", 
  "signature": "h2sU5eNp4SBPDBI8UuopvHNzQUpvtgprCm1dbmWaU1fG0OpfdO3c8axXPspDrAIcDqCvInhhOBU3WlH8VS1AqFdGpz4FojUCx6at4rKROhLla4aX6RAf-FehWStNWKcN1mPcXyarpXjj4cN7hnYID3LXGga1NARuZES8ysjAqgeRzDTmJIHRABYD0fUI4Ab-vxPJPqjxlahL5WGsBnWnysM1nUSEwMWZB8u4keA6rbCUQi4h_T0T-BuhKB5hGBPO5o8PME6W_SqDPQAHEY-kBAFCzrDDv8D2FSA-rWuz7ugU-2M9qnBa_ZseGmtTmFye_DzZ59NJr9nY6zTIWErUW8OHcjUfXtk4imTMtLdqSJjqTjyiqfGTpa_ovQ-mnASeIZGsB8_ZFrsEbA5-CUAxBuj9vgFtBUjQ6tRI-Uvl670cw6-OKeDLQ2ABQc1saEcso3L5bP5J72ICCNMPBwE6DCE9S4IF2dIBDn888pEt8SUeARgiDXn19y609N39XUGsuYmVHyx2g1F8fWUR9KhDRui5ERq4WdQc3U8MrKqOBqhaLJbLU69c1HR1i6ni67vZJ2HKHjoOPeTMB-1nIM3VBmbu6qyatVXpl2r0o7QTsxyZ5JVf15xdy3KgNcpPT9XrVn3UfA_z-uognF1gKtbqvjtVrSfUiPUttA8nrlqB1D0"
}
2017-02-01 18:22:06,994:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 400 109
2017-02-01 18:22:06,996:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Content-Type: application/problem+json
Content-Length: 109
Boulder-Request-Id: aX9Tb58L-G4PyoTxDSZDXgti8b4fevmod_cYade4mmY
Boulder-Requester: 9061929
Replay-Nonce: mxPguDx0dzdp_29Ew_rw1MhVbX0hsH4iFVSX2cRWywk
Expires: Wed, 01 Feb 2017 18:22:06 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 01 Feb 2017 18:22:06 GMT
Connection: close

{
  "type": "urn:acme:error:malformed",
  "detail": "Name does not end in a public suffix",
  "status": 400
}
2017-02-01 18:22:06,997:DEBUG:acme.client:Storing nonce: mxPguDx0dzdp_29Ew_rw1MhVbX0hsH4iFVSX2cRWywk
2017-02-01 18:22:07,000:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 626, in obtain_cert
    action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 107, in _auth_from_available
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 291, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 262, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 67, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 216, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 196, in request_challenges
    new_authz)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 671, in post
    return self._post_once(*args, **kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 684, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 570, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:malformed :: The request message was malformed :: Name does not end in a public suffix
```

**Comment by vfarcic** [comment]
@hamburml Will answer better then me since he wrote Let's Encrypt Companion. My comment is based only on observing logs.

The problem seems to come from Let's Encrypt service. It does not allow non-public domains. You can see that from the message "Name does not end in a public suffix".

**Comment by vfarcic** [comment]
Do you have a public domain you can use?

**Comment by mbaig25** [comment]
@vfarcic Yeah I noticed that as well.

I will be deploying with a public domain. Just waiting getting the domain (corporate. Takes time). 

I will update status on this if all is well or if there is another issue.

**Comment by hamburml** [comment]
@mbaig25 In your second log you have an erro message from [acme](https://github.com/ietf-wg-acme/acme/).

```
{
  "type": "urn:acme:error:malformed",
  "detail": "Name does not end in a public suffix",
  "status": 400
}
```
Let's Encrypt uses ACME to [verify](https://letsencrypt.org/docs/client-options/) that this domain is in fact yours. When they don't do this everyone could create domains for google.de for example. You need a public domain pointing to your docker swarm. Hope this helps :)

**Comment by mbaig25** [comment]
@hamburml it does help thank you :slightly_smiling_face: :

**Comment by vfarcic** [comment]
@mbaig25 Please let me know if you fixed the problem and whether this issue can be closed.

**Comment by mbaig25** [comment]
It's all good. Thanks guys. Closing issue. 🙂
