### ISSUE TITLE
Running with docker-compose outside a swarm

### ISSUE THREAD

**Issue by souliane** [vfarcic/docker-flow-proxy#204]
I want to use docker-flow-proxy without docker stack and outside a swarm first (1), and this is what I get when starting with docker-compose::
```
$ docker-compose -f docker/docker-compose-full-stack.yml run api-gw
2017/04/18 07:26:36 Starting HAProxy
2017/04/18 07:26:36 Creating configuration for the service test
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x55d63e]

goroutine 1 [running]:
panic(0x8794e0, 0xc82000e100)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
_/usr/src/myapp/registry.Consul.createConfig(0xb8d108, 0x0, 0x0, 0x9e7829, 0x9, 0x97bdc0, 0x1a, 0xc8201dc000, 0xb3, 0xc82000a03b, ...)
        /usr/src/myapp/registry/consul.go:128 +0x5fe
_/usr/src/myapp/registry.Consul.CreateConfigs(0xc820152680, 0x0, 0x0)
        /usr/src/myapp/registry/consul.go:90 +0x194
_/usr/src/myapp/registry.(*Consul).CreateConfigs(0xb8d108, 0xc820152680, 0x0, 0x0)
        <autogenerated>:4 +0xa3
_/usr/src/myapp/actions.(*Reconfigure).createConfigs(0xc82018ea00, 0x9e7829, 0x9, 0xc82018ea50, 0x0, 0x0)
        /usr/src/myapp/actions/reconfigure.go:218 +0x380
_/usr/src/myapp/actions.(*Reconfigure).Execute(0xc82018ea00, 0xb8d108, 0x0, 0x0, 0x0, 0x0)
        /usr/src/myapp/actions/reconfigure.go:69 +0x2cb
main.(*Serve).reconfigure(0xb6fd60, 0x7fe7c7093000, 0xc8201582d0, 0x0, 0x0)
        /usr/src/myapp/server.go:98 +0x441
main.(*Serve).Execute(0xb6fd60, 0xc82000f9b0, 0x0, 0x1, 0x0, 0x0)
        /usr/src/myapp/server.go:62 +0x54e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc820060180, 0xc82000a310, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/jessevdk/go-flags/parser.go:316 +0xa83
main.Args.Parse(0x0, 0x0)
        /usr/src/myapp/args.go:22 +0x296
main.main()
        /usr/src/myapp/main.go:13 +0x9a

```

Here the api-gw section in docker-compose-full-stack.yml:
```
  api-gw:
    image: vfarcic/docker-flow-proxy:1.278
    ports:
      - "8080:80"
    environment:
      - SERVICE_NAME=api-gw
      - DEBUG=true
      - DFP_SERVICE_1_SERVICE_NAME=test
      - DFP_SERVICE_1_SERVICE_PATH=..
      - DFP_SERVICE_1_PORT=80
```

If I remove the DFP_SERVICE_1_SERVICE_PATH *and* DFP_SERVICE_1_PORT from the config, it starts without crash:
```
2017/04/18 07:29:32 Starting HAProxy
2017/04/18 07:29:32 Creating configuration for the service test
2017/04/18 07:29:32 Reloading the proxy
2017/04/18 07:29:32 HAPRoxy: Proxy services started.
2017/04/18 07:29:32 Starting "Docker Flow: Proxy"
```

Could you please fix this and/or display a proper error message if the configuration is invalid?

(1) Is it possible to use docker-flow-proxy outside a swarm and without docker-flow-swarm-listener? Maybe it doesn't make a lot of sense, but the reason why we would like to do that, is that it would allow us to have a similar config and procedure for both dev and productive environment.

Thanks.

**Comment by souliane** [comment]
I have been informed that the default mode needs a consul, otherwise I can use the swarm mode outside a swarm and without docker-flow-swarm-listener - in that case I have to configure my services with the env variables. This should allow me to do what I want without using the deprecated default mode. I guess this answer my question (1).

**Comment by vfarcic** [comment]
I'll work on improving logging. In the meantime, if you're not using Consul (as you shouldn't since it's deprecated), add the env. var. `MODE=swarm` and it should work even if service is outside Swarm.

**Comment by vfarcic** [comment]
Closing due to inactivity. Please post a comment if you'd like to reopen this issue.
