### ISSUE TITLE
Not able to register in automatic mode

### ISSUE THREAD

**Issue by alexanderkjeldaas** [vfarcic/docker-flow-proxy#76]
This is what the logs look like for the proxy:
```
2016/12/06 23:12:21 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:12:30 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:12:35 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:12:40 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:12:45 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:12:50 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:12:56 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:13:01 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:13:06 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:13:11 Processing request /v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
```

Logging in and trying to play with the `docker-flow-proxy` executable, it looks a bit flaky:

```
/ # /usr/local/bin/docker-flow-proxy reconfigure -s app-backend_app-backend -m swarm
2016/12/06 23:23:32 Creating configuration for the service app-backend_app-backend
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x401737]

goroutine 1 [running]:
panic(0x80f9e0, 0xc82000e0e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*Reconfigure).Execute(0xacc980, 0xc820014460, 0x0, 0x5, 0x0, 0x0)
	/usr/src/myapp/reconfigure.go:89 +0x2e7
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc82000a240, 0xc82000a0d0, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/jessevdk/go-flags/parser.go:316 +0xa83
main.Args.Parse(0x0, 0x0)
	/usr/src/myapp/args.go:21 +0x296
main.main()
	/usr/src/myapp/main.go:4 +0x24
```

The swarm listener:

```
2016/12/06 23:09:00 Starting Docker Flow: Swarm Listener v0.6
2016/12/06 23:09:00 Starting iterations
2016/12/06 23:09:00 Sending service created notification to http://app-backend_proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083
2016/12/06 23:09:04 Sending service created notification to http://app-backend_proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&distribute=true&port=8083&servicePath=/
2016/12/06 23:09:49 ERROR: Request http://app-backend_proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&distribute=true&port=8083&servicePath=/ returned status code 500
{"Status":"NOK","Message":"Could not perform DNS tasks.proxy lookup","ServiceName":"app-backend_app-backend","AclName":"","ServiceColor":"","ServicePath":["/"],"ConsulTemplateFePath":"","ConsulTemplateBePath":"","PathType":"","SkipCheck":false,"Mode":"swarm","Port":"8083","Distribute":true,"Users":null}
2016/12/06 23:13:11 ERROR: Request http://app-backend_proxy:8080/v1/docker-flow-proxy/reconfigure?serviceName=app-backend_app-backend&servicePath=/&distribute=true&port=8083 returned status code 500
{"Status":"NOK","Message":"Could not perform DNS tasks.proxy lookup","ServiceName":"app-backend_app-backend","AclName":"","ServiceColor":"","ServicePath":["/"],"ConsulTemplateFePath":"","ConsulTemplateBePath":"","PathType":"","SkipCheck":false,"Mode":"swarm","Port":"8083","Distribute":true,"Users":null}
```

The errors look legit as they probably appear during service startup when DNS for the backend service is not available.

```
$ docker exec -it app-backend_swarm-listener.1.ad4p9wxi0r1pua729odvroxk7 drill app-backend_app-backend
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 48823
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; app-backend_app-backend.	IN	A

;; ANSWER SECTION:
app-backend_app-backend.	600	IN	A	10.0.0.8

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Tue Dec  6 23:30:42 2016
;; MSG SIZE  rcvd: 80
```

This is also available form the proxy:

```
$ docker exec -it app-backend_proxy.1.6489gobavbr41e6g65528a1pa drill app-backend_app-backend
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 49068
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; app-backend_app-backend.	IN	A

;; ANSWER SECTION:
app-backend_app-backend.	600	IN	A	10.0.0.8

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Tue Dec  6 23:31:56 2016
;; MSG SIZE  rcvd: 80
```

**Comment by vfarcic** [comment]
When I proxy instance receives a request to reconfigure itself, it'll resend it to all the instances. That way, all have the same data. To do that, the proxy queries internal DNS to find the IPs of all the instances of the proxy service. By default, it assumes that the service is called `proxy`. You can see that from the log entry that says "Could not perform DNS tasks.proxy lookup". If the name is different (in your case `app-backend_proxy`, you'll need to specify that as the environment variable `SERVICE_NAME`. Can you please recreate the service with the `-e SERVICE_NAME=app-backend_proxy`.

Can you please try it out and let me know how it went.

Feel free to ping me on Skype or HangOuts. If you can share your screen, I'd be more than happy to help.

**Comment by alexanderkjeldaas** [comment]
Thanks! That worked.  I've proposed an edit to the error message for this issue.  It wasn't clear to me that "task.proxy"-part of the error message was related to the name of the proxy.

**Comment by vfarcic** [comment]
Thank you
